# Generated by Django 5.1.6 on 2025-04-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproduct',
            name='total_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
