# Generated by Django 5.1.6 on 2025-04-24 09:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_alter_myproduct_total_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproduct',
            name='pdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
