# Generated by Django 5.1.6 on 2025-04-24 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_alter_myproduct_pdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproduct',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facebook.category'),
        ),
    ]
