# Generated by Django 5.1.6 on 2025-04-24 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0004_alter_myproduct_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproduct',
            name='subcategory_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facebook.subcategory'),
        ),
    ]
