# Generated by Django 5.1.6 on 2025-04-24 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0005_alter_myproduct_subcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproduct',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
