# Generated by Django 5.1.6 on 2025-04-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0006_myproduct_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
