# Generated by Django 5.1.6 on 2025-04-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0009_cart_myorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproduct',
            name='cname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
