# Generated by Django 5.1.6 on 2025-04-25 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0010_myproduct_cname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myorders',
            new_name='myorder',
        ),
    ]
