# Generated by Django 5.1.6 on 2025-04-25 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0011_rename_myorders_myorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myproduct',
            name='cname',
        ),
    ]
