# Generated by Django 5.1.6 on 2025-04-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0013_subcategory_subcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='subcategory_image',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
