# Generated by Django 5.1.6 on 2025-04-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0014_remove_subcategory_subcategory_image_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cpic',
            field=models.ImageField(null=True, upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='product_pic',
            field=models.ImageField(null=True, upload_to='product/'),
        ),
    ]
