# Generated by Django 5.1.6 on 2025-04-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0015_alter_category_cpic_alter_myproduct_product_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='subcategory_image',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory_image/'),
        ),
    ]
