# Generated by Django 5.1.6 on 2025-04-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0016_subcategory_subcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='subcategory_image',
        ),
        migrations.AlterField(
            model_name='category',
            name='cpic',
            field=models.ImageField(blank=True, null=True, upload_to='static/category/'),
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='product_pic',
            field=models.ImageField(null=True, upload_to='static/product/'),
        ),
    ]
