# Generated by Django 5.1.6 on 2025-05-01 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0018_category_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facebook.myproduct'),
            preserve_default=False,
        ),
    ]
