# Generated by Django 5.1.6 on 2025-05-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0020_myproduct_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproduct',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
